"""
Problem: 389. Find the Difference
Link: https://leetcode.com/problems/find-the-difference/

Level: Easy

Description:
You are given two strings s and t.
String t is generated by shuffling string s and then adding one extra character at a random position.

Return the extra character that was added to t.

Example:

Input: s = "abcd", t = "abcde"
Output: "e

"""
"""approch 1: using hash table"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        d = {}
        for i in s:
            if i in d:
                d[i]+=1
            else:
                d[i]=1
        for i in t:
            if i in d and d[i]!=0:
                d[i]-=1
            else:
                return i

"""approch 2 : using count method"""
class Solution(object):
    def findTheDifference(self, s, t):
        for i in t:
            if t.count(i)> s.count(i):
                return i